using Hairball.Core;
using System.Numerics;
internal static class HumanCustomerTests
{
    public static void Run(Action<string,Action> test,Action<bool,string> check)
    {
        void C(bool b,string m="human customer assertion")=>check(b,m);
        Session World(int count=4){var s=new Session();s.State.Experiment.Variant=ExperimentVariant.B;for(int i=1;i<=count;i++)s.AddPlayer(i,"P"+i);s.StartMatch();s.State.Phase=Phase.Build;s.State.Remaining=150;return s;}
        void Press(Session s,int actor,Buttons buttons){var p=s.State.Player(actor)!;s.Inputs[actor]=(default,p.Yaw,p.Pitch,buttons);s.Tick(.02f);s.Inputs[actor]=(default,p.Yaw,p.Pitch,Buttons.None);s.Tick(.02f);}
        test("p11 actual role count, join-order rotation, no secret for customer",()=>{for(int n=1;n<=4;n++){var s=World(n);s.Tick(.01f);C(s.State.Experiment.CustomerActor==(n>1?1:0));C(Session.BarberCount(s.State)==(n>1?n-1:n));C(s.State.Props.Count(p=>p.Coop!=CoopKind.None)==(n>=3?5:0));C(s.OwnTask(1)==null||n==1);C(s.OwnTarget(1)!=null||n==1);C(s.OwnTarget(2)==null);s.NextRound();C(s.State.Experiment.CustomerActor==(n>1?2:0));}});
        test("p11 debug AI and disconnect takeover never reassign private card midround",()=>{var s=World();s.CustomerDisconnected(1);C(s.State.Experiment.CustomerActor==0&&!s.State.Player(1)!.Customer&&s.OwnTarget(1)==null);s.State.Player(1)!.NetworkAway=false;s.Tick(.1f);C(s.State.Experiment.CustomerActor==0);s.ForceAI=true;s.NextRound();C(!s.State.Players.Any(p=>p.Customer)&&Session.BarberCount(s.State)==4);});
        test("p11 target absent from broadcast and replay before actual reveal",()=>{var s=World();s.Tick(.2f);var copy=Wire.Decode<WorldState>(Wire.Encode(s.State));C(copy.Experiment.ResultTarget==null&&copy.Experiment.ResultStyle.Count==0);C(s.Replay.Rolling.All(f=>f.Experiment.ResultTarget==null));C(s.OwnTarget(1)==s.CurrentTarget&&s.OwnTarget(2)==null);});
        test("p11 shared head and attachments reject every customer query",()=>{var s=World();var p=s.State.Player(1)!;p.Standing=true;var wig=s.State.Heads.First(h=>h.Loose);wig.AttachedTo=0;wig.Position=s.State.SharedHead.Position;var h=s.State.SharedHead;p.Position=h.Position+new Vector3(0,-1.7f,2);p.Yaw=0;p.Pitch=0;for(int d=0;d<11;d++)C(ToolQuery.EffectHits(s.State,p,d,false,Session.Aim(p),5).All(x=>!HumanCustomer.Self(s.State,p,x.head)));C(ToolQuery.Find(s.State,p,0,false,Session.Aim(p),5).All(x=>!HumanCustomer.Self(s.State,p,s.State.Heads.First(h=>h.Id==x.HeadId))));});
        test("p11 eyes stay clamped while expressions move authority, brace scales .22",()=>{var s=World();var p=s.State.Player(1)!;s.Inputs[1]=(default,20,2,Buttons.Primary);s.Tick(.15f);C(Math.Abs(p.Pitch)<=MathF.PI*2/9+.001f&&Math.Abs(MathF.IEEERemainder(p.Yaw-HumanCustomer.SeatYaw(s.State),MathF.Tau))<=MathF.PI/3+.001f);s.State.Time=p.ExpressionAt+.15f;var full=HumanCustomer.Expression(s.State);s.State.Player(2)!.Bracing=true;var braced=HumanCustomer.Expression(s.State);C(Math.Abs(full.X-MathF.PI/15)<.001f&&Vector3.Distance(braced,full*.22f)<.001f);p.Standing=true;p.Position=new(2,0,1);CustomerMotion.Apply(s.State);C(Vector3.Distance(s.State.SharedHead.Position,Session.Eye(p))<.4f);});
        test("p11 rising requires edges, host caps 12 presses/sec, 5 sec retry",()=>{var s=World();Press(s,1,Buttons.Stand);C(s.State.Experiment.StandActive);for(int i=0;i<4;i++)Press(s,1,Buttons.Stand);C(s.State.Player(1)!.Standing);s.NextRound();s.State.Phase=Phase.Build;var p=s.State.Player(2)!;s.Inputs[2]=(default,p.Yaw,p.Pitch,Buttons.Stand);s.Tick(.02f);for(int i=0;i<180;i++)s.Tick(.02f);C(!p.Standing&&!s.State.Experiment.StandActive&&s.State.Experiment.StandCooldown>s.State.Time);Press(s,2,Buttons.Stand);C(!s.State.Experiment.StandActive);});
        test("p11 pressure stacks participating hands, never idle nearby barbers",()=>{var s=World();var c=s.State.Player(1)!;for(int id=2;id<=4;id++){var p=s.State.Player(id)!;p.Position=new((id-3)*.25f,0,1.3f);var d=Vector3.Normalize(s.State.SharedHead.Position-Session.Eye(p));p.Yaw=MathF.Atan2(-d.X,-d.Z);p.Pitch=MathF.Asin(d.Y);}Press(s,1,Buttons.Stand);float progress=s.State.Experiment.StandProgress;Press(s,4,Buttons.Interact);C(Math.Abs(progress-s.State.Experiment.StandProgress-.12f)<.001f,"one participating hand has full force");progress=s.State.Experiment.StandProgress;Press(s,2,Buttons.Interact);C(Math.Abs(progress-s.State.Experiment.StandProgress-.072f)<.001f);progress=s.State.Experiment.StandProgress;Press(s,3,Buttons.Interact);C(Math.Abs(progress-s.State.Experiment.StandProgress-.048f)<.001f);});
        test("p11 authority ignores a thirteenth rising edge within one second",()=>{var s=World(2);var c=s.State.Player(1)!;var b=s.State.Player(2)!;b.Position=new(0,0,1.3f);var d=Vector3.Normalize(s.State.SharedHead.Position-Session.Eye(b));b.Yaw=MathF.Atan2(-d.X,-d.Z);b.Pitch=MathF.Asin(d.Y);for(int i=0;i<12;i++){s.Inputs[1]=(default,c.Yaw,c.Pitch,Buttons.Stand);s.Inputs[2]=(default,b.Yaw,b.Pitch,Buttons.Interact);s.Tick(.005f);s.Inputs[1]=(default,c.Yaw,c.Pitch,0);s.Inputs[2]=(default,b.Yaw,b.Pitch,0);s.Tick(.005f);}C(s.State.Experiment.StandActive);float balance=s.State.Experiment.StandProgress;s.Inputs[1]=(default,c.Yaw,c.Pitch,Buttons.Stand);s.Tick(.005f);C(Math.Abs(s.State.Experiment.StandProgress-balance)<.001f,"13th tap must not count");});
        test("p11 human departure is body driven and judges locally at 20 seconds",()=>{var s=World(2);s.State.Remaining=0;s.Tick(.01f);C(s.State.Experiment.StandActive);for(int i=0;i<5;i++)Press(s,1,Buttons.Stand);var p=s.State.Player(1)!;p.Position=new(1.5f,0,1);for(int i=0;i<18;i++)s.Tick(1);C(!s.State.Experiment.Resolved&&p.Position==new Vector3(1.5f,0,1));s.Tick(2);C(s.State.Experiment.Resolved&&s.State.Experiment.ResultTarget!=null);});
        test("p11 actual return cut changes barber material while settled target and pay stay frozen",()=>{var s=World(2);s.State.Remaining=0;s.Tick(.01f);for(int i=0;i<201;i++)s.Tick(.1f);var p=s.State.Player(1)!;var barber=s.State.Player(2)!;p.Standing=true;p.Position=barber.Position+new Vector3(0,0,1.2f);p.Yaw=0;p.Pitch=0;var h=s.State.Barber(barber.Slot);float before=h.Mass;int wallet=s.State.Job.Wallet;var checks=s.State.Experiment.ResultStyle.ToArray();for(int i=0;i<20;i++){s.Inputs[1]=(default,p.Yaw,p.Pitch,Buttons.Primary);s.Tick(.02f);}C(h.Mass<before,"return clipper must remove actual density");C(s.State.Job.Wallet==wallet&&s.State.Experiment.ResultStyle.SequenceEqual(checks));});
        test("p11 return cut and pie/poop/like do not alter settled money or success",()=>{var s=World(2);s.State.Remaining=0;s.Tick(.01f);for(int i=0;i<201;i++)s.Tick(.1f);var e=s.State.Experiment;int wallet=s.State.Job.Wallet;bool success=e.Success;float tip=e.Tip;e.ReturnCut=false;s.State.Player(1)!.Standing=true;s.State.Player(1)!.Position=new(3,0,2);s.State.Player(1)!.Yaw=0;Press(s,1,Buttons.Primary);Press(s,1,Buttons.Primary);C(s.State.Player(1)!.PieUsed&&s.State.Projectiles.Count<=1);Press(s,1,Buttons.Secondary);C(s.State.Player(1)!.PoopUsed);C(s.State.Job.Wallet==wallet&&e.Success==success&&e.Tip==tip&&e.ResultStyle.Count>0);});
    }
}
