using Hairball.Core;
using System.Numerics;
internal static class TwistTests
{
    public static void Run(Action<string,Action> test,Action<bool,string> check)
    {
        void C(bool b,string m="twist assertion")=>check(b,m);
        Session World(TwistKind kind,int n=4){var s=new Session{DebugCustomerActor=1,TwistPicker=_=>kind};s.State.Experiment.Variant=ExperimentVariant.B;for(int id=1;id<=n;id++){var p=s.AddPlayer(id,"P"+id)!;p.AllowViewChanges=true;}s.StartMatch();C(s.State.Twist.Kind==TwistKind.None,"round one has no twist");s.NextRound();s.State.Phase=Phase.Build;return s;}
        test("p12 all sixteen cards declare conditions and enforce the mode matrix",()=>{C(TwistCards.All.Length==16);foreach(var kind in Enum.GetValues<TwistKind>().Where(k=>k!=TwistKind.None))for(int n=1;n<=4;n++){var s=World(kind,n);var card=TwistCards.Card(kind)!;C((s.State.Twist.Kind==kind)==TwistCards.Eligible(card,s.State),kind+" "+n);C(card.Chinese.Length>0&&card.English.Length>0&&card.Rule.Length>0);}});
        test("p12 comfort cards excluded by default; adjacent draw changes category",()=>{var s=World(TwistKind.None);foreach(var p in s.State.Players)p.AllowViewChanges=false;for(int seed=0;seed<150;seed++){var k=TwistCards.Draw(s.State,seed,TwistKind.Fan);C(!TwistCards.Card(k)!.Comfort);C(TwistCards.Card(k)!.Category!='D');}s.TwistsEnabled=false;s.NextRound();C(s.State.Twist.Kind==TwistKind.None);});
        test("p12 reverse and family targets remain private in snapshots and replay",()=>{foreach(var k in new[]{TwistKind.Reverse,TwistKind.Family,TwistKind.SplitInfo}){var s=World(k);C(s.State.Twist.ResultFamily==null&&s.State.Experiment.ResultTarget==null);C(s.OwnTarget(2)!=null||k==TwistKind.Family);if(k!=TwistKind.Family)C(s.OwnTarget(1)==null);var copy=Wire.Decode<WorldState>(Wire.Encode(s.State));C(copy.Twist.ResultFamily==null&&copy.Experiment.ResultTarget==null);s.Tick(.15f);C(s.Replay.Rolling.All(f=>f.Twist.ResultFamily==null));if(k==TwistKind.Reverse){C(s.OwnOptions(1).Length==4&&s.OwnOptions(2).Length==0);C(s.OwnOptions(1).Contains(s.CurrentTarget!.Id));C(!s.GuessTarget(2,0)&&!s.GuessTarget(1,4));}if(k==TwistKind.SplitInfo)C(s.OwnRecipe(1).Chinese.Length>0&&s.OwnRecipe(2).Chinese=="");}});
        test("p12 family and helper cannot edit hair through any tool query",()=>{foreach(var k in new[]{TwistKind.Family,TwistKind.CustomerHelper}){var s=World(k);var p=s.State.Player(k==TwistKind.Family?s.State.Twist.FamilyActor:1)!;p.Standing=true;p.Position=new(0,0,2);p.Yaw=0;for(int d=0;d<11;d++)C(ToolQuery.EffectHits(s.State,p,d,false,Session.Aim(p),5).Count==0);C(ToolQuery.Find(s.State,p,0,false,Session.Aim(p),5).Count==0);}});
        test("p12 nod/shake restrictions and presentation never mutate head authority",()=>{var s=World(TwistKind.PropsOnly);var p=s.State.Player(1)!;s.Inputs[1]=(default,p.Yaw,0,Buttons.Primary|Buttons.ChairUp);s.Tick(.02f);C(p.Expression==0&&!p.HeadLook);s=World(TwistKind.Contrarian);p=s.State.Player(1)!;p.Expression=1;p.ExpressionAt=s.State.Time-.15f;var before=Wire.Encode(s.State);var d=TwistCards.DisplayDelta(s.State,2);C(Math.Abs(d.X)>.1f&&Math.Abs(d.Y)>.1f);C(TwistCards.DisplayDelta(s.State,1)==Vector3.Zero&&Wire.Encode(s.State).SequenceEqual(before));s.State.Twist.Kind=TwistKind.OneViewer;s.State.Twist.ViewerActor=2;C(TwistCards.DisplayDelta(s.State,2)==Vector3.Zero&&TwistCards.DisplayDelta(s.State,3).X<-.1f);});
        test("p12 question counter debounces one held prop and caps six",()=>{var s=World(TwistKind.LimitedQuestions);var prop=s.State.Props.First(p=>p.Gesture>=0);prop.Holder=2;C(s.PropQuestion(prop));C(!s.PropQuestion(prop)&&s.State.Twist.Questions==1);for(int i=0;i<9;i++){prop.Id++;s.PropQuestion(prop);}s.State.Time+=1.1f;C(s.State.Twist.Questions==6&&!TwistCards.AllowExpression(s.State,s.State.Player(1)!));});
        test("p12 ten-second miniature edits actual material and then locks on table",()=>{var s=World(TwistKind.MiniDemo);var p=s.State.Player(1)!;var model=s.State.Heads.First(h=>h.Miniature);p.Yaw=MathF.PI;p.Pitch=.12f;s.Inputs[1]=(default,p.Yaw,p.Pitch,Buttons.Primary);float before=model.Mass;for(int i=0;i<15;i++)s.Tick(.02f);C(model.Mass!=before,"assigned tool must affect actual demo volume");s.State.Time+=10;s.Tick(.02f);C(model.Locked&&model.Position.X==-3&&p.Held==-1);});
        test("p12 fog stores bounded host line segments and expires in twenty seconds",()=>{var s=World(TwistKind.FogMirror);var p=s.State.Player(1)!;p.Yaw=MathF.PI;p.Pitch=.06f;var tool=s.State.Tools.First(t=>t.Definition==3);tool.Holder=1;p.Held=tool.Id;s.UseTool(p,false);C(s.State.Twist.FogUntil>s.State.Time+19);s.Drop(p);s.Inputs[1]=(default,MathF.PI,.06f,Buttons.Primary);s.Tick(.02f);s.Inputs[1]=(default,MathF.PI+.05f,.06f,Buttons.Primary);s.Tick(.02f);C(s.State.Twist.Lines.Count==1);s.State.Time+=21;int count=s.State.Twist.Lines.Count;s.Tick(.02f);C(s.State.Twist.Lines.Count==count);});
        test("p12 object gravity scales without altering player movement",()=>{var s=World(TwistKind.LowGravity);C(TwistCards.Gravity(s.State)==.35f);var prop=s.State.Props.First(p=>p.Gesture>=0);prop.Released=true;prop.Position=new(4,3,4);prop.Velocity=default;PhysicalProps.Tick(s.State,.1f,null);C(Math.Abs(prop.Velocity.Y+.175f)<.001f);s.State.Phase=Phase.Results;C(TwistCards.Gravity(s.State)==1);});
        test("p12 family settles two cards with one penalty and one nonnegative floor",()=>{foreach(int penalty in new[]{15,100}){var s=World(TwistKind.Family);s.TargetPicker=_=>26;s.FamilyPicker=_=>29;s.NextRound();s.State.Phase=Phase.Build;s.State.Remaining=0;s.State.Job.Penalty=penalty;foreach(var p in s.State.SharedHead.Patches)p.Glue=1;C(s.State.Twist.ResultFamily==null&&s.OwnTarget(s.State.Twist.FamilyActor)?.Id==30);for(int i=0;i<211;i++)s.Tick(.1f);C(s.State.Twist.ResultFamily?.Id==30&&s.State.Twist.FamilyChecks.Single().Match);C(s.State.Experiment.ResultStyle.Single().Match&&!s.State.Experiment.Success&&s.State.Experiment.BasePay==0);C(s.State.Experiment.Tip==(penalty==15?5:0),"both matches total20; penalty applied once before floor");}});
        test("p12 reverse correct guess gives ten tips after functional decision",()=>{var s=World(TwistKind.Reverse);int choice=Array.IndexOf(s.OwnOptions(1),s.CurrentTarget!.Id);C(s.GuessTarget(1,choice));s.State.Remaining=0;for(int i=0;i<211;i++)s.Tick(.1f);C(s.State.Experiment.Resolved&&s.State.Twist.GuessCorrect&&!s.State.Experiment.Success);C(s.State.Experiment.Tip>=10);});
    }
}
