using Hairball.Core;
namespace Hairball.Tests;
public static class VoiceTests
{
    public static void Run(Action<string,Action> test,Action<bool,string> check)
    {
        float[] Tone(int frame=0)=>Enumerable.Range(0,960).Select(i=>(float)(.15*Math.Sin(2*Math.PI*220*(frame*960+i)/48000))).ToArray();
        test("voice Opus real encode decode and PLC",()=>{var e=new VoiceEncoder();var d=new VoiceDecoder();float energy=0;for(int i=0;i<8;i++){var p=e.Process(Tone(i),0,false,0,true,false,false)!;check(p.Kind==VoiceKind.Opus&&p.Payload.Length<=160,"Opus");energy+=d.Decode(p.Payload).Sum(x=>x*x);}check(energy>1,"decoded tone");check(d.Decode(null).All(float.IsFinite),"PLC");});
        test("voice injected identity cannot pass another speaker's tone",()=>{var pcm=Enumerable.Range(0,960).Select(i=>(float)(.13*Math.Sin(2*Math.PI*320*i/48000))).ToArray();check(VoiceProbe.Matches(pcm,2,[1,2,3,4]),"correct identity");check(!VoiceProbe.Matches(pcm,1,[1,2,3,4]),"wrong identity rejected despite spectral leakage");});
        test("voice filtered role never calls Opus",()=>{var e=new VoiceEncoder();for(int i=0;i<100;i++){var p=e.Process(Tone(i),(uint)(i*20),true,0,true,false,false);if(p!=null)check(p.Kind==VoiceKind.Features&&p.Payload.Length==4,"only features");}check(e.OpusPackets==0&&e.FeaturePackets==50,"privacy");});
        test("voice mute PTT gate prevent transmission",()=>{var e=new VoiceEncoder();check(e.Process(Tone(),0,false,0,false,false,false)==null,"disabled");check(e.Process(Tone(),0,false,0,true,true,false)==null,"PTT");check(e.Process(new float[960],0,false,0,true,false,false)==null,"silence");check(e.OpusPackets==0,"none encoded");});
        test("voice features quantize and deterministic unworded synthesis",()=>{var f=new VoiceFeature(.37f,220,true,true);var g=VoiceFeature.Unpack(f.Pack());check(Math.Abs(f.Loudness-g.Loudness)<.005&&Math.Abs(f.Pitch-g.Pitch)<3,"quantization");var a=SpeciesVoice.Synthesize(g,0,7);check(a.SequenceEqual(SpeciesVoice.Synthesize(g,0,7))&&a.All(float.IsFinite)&&a.Any(x=>Math.Abs(x)>.01),"synthesis");check(!a.SequenceEqual(SpeciesVoice.Synthesize(g,VoiceSpecies.Bird,7)),"species differ");});
        test("voice synthesis uses onset and voiced features",()=>{var f=new VoiceFeature(.4f,220,true,true);var a=SpeciesVoice.Synthesize(f,0,7);check(!a.SequenceEqual(SpeciesVoice.Synthesize(f with{Onset=false},0,7)),"onset articulation");check(!a.SequenceEqual(SpeciesVoice.Synthesize(f with{Voiced=false},0,7)),"unvoiced articulation");});
        test("voice wire bounds and filtered relay rejects Opus",()=>{var p=new VoicePacket(VoiceKind.Features,0,1,20,new VoiceFeature(.5f,180,true,false).Pack());check(VoicePacket.Parse(p.Encode())!.Payload.SequenceEqual(p.Payload),"roundtrip");check(VoicePacket.Parse(new byte[500])==null,"oversize");check(!VoiceRoute.Allowed(p with{Kind=VoiceKind.Opus},true),"relay privacy");check(VoiceRoute.Recipients([1,2,3,4],2).SequenceEqual([1,3,4]),"no sender echo");});
        test("voice jitter reorders, bounded adaptive delay, late drop and PLC gap",()=>{var j=new VoiceJitter();VoicePacket P(uint n)=>new(VoiceKind.Opus,0,n,n*20,[1]);j.Add(P(1),1);j.Add(P(3),1.04);j.Add(P(2),1.045);check(j.Pop(1.07,out var a,out _)&&a!.Sequence==1,"first");check(j.Pop(1.09,out a,out _)&&a!.Sequence==2,"reordered");check(!j.Add(P(1),1.1),"late");j.Pop(1.11,out a,out _);check(a!.Sequence==3,"third");check(j.Pop(1.13,out a,out _)&&a==null&&j.Lost==1,"PLC gap");check(j.BufferSeconds>=.06&&j.BufferSeconds<=.12,"buffer bounded");j.Add(P(90),2);check(j.Pop(2.2,out a,out _)&&a!.Sequence==90,"resume after silence");});
        test("voice jitter sheds stale startup instead of retaining a permanent backlog",()=>{var j=new VoiceJitter();for(uint n=1;n<=20;n++){double arrival=n<=2?.32+n*.02:.12+n*.02;j.Add(new(VoiceKind.Opus,0,n,n*20,[1]),Math.Max(.36,arrival));}check(j.Pop(.53,out var p,out _)&&p!=null&&p.Sequence>10,"stale startup shed");check(j.CatchUp>0&&.53-p!.Timestamp/1000d<.24,"bounded age after resync");});
    }
}
