using Hairball.Core;
using System.Numerics;
internal static class WorldTests
{
    public static void Run(Action<string,Action> test,Action<bool,string> check)
    {
        void C(bool b,string m="world expansion assertion")=>check(b,m);
        Session World(int count=1){var s=new Session{CatPicker=_=>true};s.State.Experiment.Variant=ExperimentVariant.B;for(int id=1;id<=count;id++)s.AddPlayer(id,"P"+id);s.StartMatch();s.State.Phase=Phase.Build;s.State.Remaining=150;return s;}
        test("p13 cat seeded frequency, host off, telegraph delay and two-action cap",()=>{int count=Enumerable.Range(0,10000).Count(ShopCat.Appears);C(count>3300&&count<3700);var s=World();C(ShopCat.Prop(s.State)!=null);C(s.BeginCatAction(CatAction.Sleep));s.Tick(1.49f);C(s.State.Cat.Mode==CatMode.Telegraph&&s.State.Cat.Actions==0);s.Tick(.02f);C(s.State.Cat.Mode==CatMode.Sleeping&&s.State.Cat.Actions==1);C(s.BeginCatAction(CatAction.Swat));s.Tick(1.51f);C(s.State.Cat.Actions==2&&!s.BeginCatAction(CatAction.Sleep));s.CatEnabled=false;s.NextRound();C(s.State.Cat.Mode==CatMode.Absent);});
        test("p13 sleeping cat adds actual balance weight and swats recoverable commission",()=>{var s=World();var prop=s.State.Props.First(p=>p.Id==s.State.Experiment.HelicopterId);prop.Attached=true;prop.Local=new(.48f,.8f,0);prop.Position=s.State.SharedHead.ToWorld(prop.Local);float offset=PartyBalance.Offset(s.State);s.BeginCatAction(CatAction.Sleep);s.Tick(1.51f);float loaded=PartyBalance.Offset(s.State);s.State.Cat.Mode=CatMode.Idle;float unloaded=PartyBalance.Offset(s.State);s.State.Cat.Mode=CatMode.Sleeping;C(ShopCat.Weight(s.State)==2.5f&&loaded>unloaded,"cat must contribute to balance independent of fallen commission");C(!prop.Attached&&prop.Released&&s.State.Props.Contains(prop));});
        test("p13 cat stealing clippings conserves material through E rescue",()=>{var s=World();DebrisSystem.Deposit(s.State.Debris,new(-3,.015f,2),.5f,new());var pile=s.State.Debris.Piles.Single();s.BeginCatAction(CatAction.Steal,pile.Id);s.Tick(1.51f);C(Math.Abs(s.State.Cat.HairMass-.2f)<.001f);C(Math.Abs(s.State.Debris.Mass+s.State.Cat.HairMass-.5f)<.001f);var p=s.State.Player(1)!;var cat=ShopCat.Prop(s.State)!;p.Position=cat.Position+new Vector3(0,-1.7f,1);p.Yaw=0;p.Pitch=.1f;C(s.HandleCat(p));C(s.State.Cat.HairMass==0&&Math.Abs(s.State.Debris.Mass-.5f)<.001f&&cat.Holder==p.Id);});
        test("p13 cat releases stolen light props when blown or carried",()=>{var s=World();var prop=s.State.Props.First(p=>p.Gesture>=0);s.BeginCatAction(CatAction.Steal,prop.Id);s.Tick(1.51f);C(prop.Holder==-1);var cat=ShopCat.Prop(s.State)!;var p=s.State.Player(1)!;p.Position=cat.Position+new Vector3(0,-1.7f,1);p.Yaw=0;p.Pitch=.1f;C(s.HandleCat(p));C(prop.Holder==0&&prop.Released);});
        test("p13 blower and thrown light props rescue and lure the cat",()=>{var s=World();s.BeginCatAction(CatAction.Sleep);s.Tick(1.51f);var cat=ShopCat.Prop(s.State)!;var p=s.State.Player(1)!;p.Position=cat.Position+new Vector3(0,-1.7f,1);p.Yaw=0;p.Pitch=.1f;p.Held=3;s.State.Tools[3].Holder=1;s.UseTool(p,false);C(s.State.Cat.Mode==CatMode.Fleeing&&!cat.Attached);s=World();s.BeginCatAction(CatAction.Sleep);s.Tick(1.51f);cat=ShopCat.Prop(s.State)!;var prop=s.State.Props.First(p=>p.Gesture>=0);prop.Position=cat.Position+Vector3.UnitZ*.5f;prop.ThrownAt=s.State.Time;prop.Thrower=1;prop.Released=true;s.Tick(.02f);C(s.State.Cat.Mode==CatMode.Fleeing&&s.State.Cat.LuredUntil>s.State.Time);});
        test("p13 actual hot blower releases a glued hand bond without body force",()=>{var s=World();var p=s.State.Player(1)!;p.AllowDrag=true;p.Position=new(0,0,1.2f);p.Held=0;var t=s.State.Tools[0];t.Holder=1;t.HitHair=true;t.Contact=s.State.SharedHead.Position;t.ContactHead=0;t.LastUse=s.State.Time;foreach(var patch in s.State.SharedHead.Patches)patch.Glue=1;s.Tick(.01f);C(p.GlueHead);var rescuer=s.AddPlayer(2,"Rescuer")!;rescuer.Position=p.Position+Vector3.UnitZ*1.4f;var aim=Vector3.Normalize(p.Position+Vector3.UnitY*1.1f-Session.Eye(rescuer));rescuer.Yaw=MathF.Atan2(-aim.X,-aim.Z);rescuer.Pitch=MathF.Asin(aim.Y);rescuer.Held=3;s.State.Tools[3].Holder=2;s.UseTool(rescuer,true);s.Tick(.01f);C(!p.GlueHead&&p.GlueUntil==0&&p.Impulse==Vector3.Zero);});
        test("p13 AI dozes after twenty quiet seconds and novel sound wakes; humans excluded",()=>{var s=World();for(int i=0;i<215;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness>.1f);float before=s.State.SharedHead.Rotation.X;C(before>0&&before<=MathF.PI/18+.01f);s.Hear(new(3,2,0),1,"new_chime");C(s.State.Experiment.Drowsiness==0&&s.State.Experiment.Attention.Cause.StartsWith("wake:"));s=World(2);for(int i=0;i<250;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness==0);});
        test("AI repeated sound stays alert without repeated startle",()=>{var s=World();for(int i=0;i<300;i++){s.Hear(new(3,2,0),1,"same_motor");s.Tick(.1f);}C(s.State.Experiment.Drowsiness==0);C(s.State.Customers[0].ReactionCount==1,"habituation still suppresses reactions");for(int i=0;i<215;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness>.1f,"quiet after activity still dozes");});
        test("AI continuous motor and actual customer contact stay alert; misses and own hair do not",()=>{
            var s=World();var p=s.State.Player(1)!;p.Position=new(0,0,2);p.Pitch=1.4f;p.Held=3;s.State.Tools[3].Holder=1;
            for(int i=0;i<240;i++){s.UseTool(p,false);s.Tick(.1f);}C(s.State.Experiment.Drowsiness==0,"continuous motor onset suppression must not imply silence");
            foreach(int contact in new[]{0,p.Slot*2+1,-1}){s=World();p=s.State.Player(1)!;p.Held=0;var t=s.State.Tools[0];t.Holder=1;t.ContactHead=contact;t.HitHair=contact>=0;for(int i=0;i<240;i++){t.LastUse=s.State.Time;s.Tick(.1f);}C(contact==0?s.State.Experiment.Drowsiness==0:s.State.Experiment.Drowsiness>.1f,"only this customer's real contact refreshes activity");}
        });
        void Face(Session s){var p=s.State.Player(1)!;p.Position=new(0,0,1.3f);var dir=Vector3.Normalize(Session.CustomerSlapPoint(s.State)-Session.Eye(p));p.Yaw=MathF.Atan2(-dir.X,-dir.Z);p.Pitch=MathF.Asin(dir.Y);}
        void Click(Session s,Buttons buttons=Buttons.Primary){var p=s.State.Player(1)!;s.Inputs[1]=(default,p.Yaw,p.Pitch,buttons);s.Tick(.02f);}
        Session Sleeping(){var s=World();for(int i=0;i<240;i++)s.Tick(.1f);Face(s);return s;}
        test("AI empty hand primary slap wakes via authoritative input, preserves material and gives twenty seconds",()=>{var s=Sleeping();C(Session.CanSlapAI(s.State,s.State.Player(1)!));float mass=s.State.SharedHead.Mass,before=s.State.SharedHead.Rotation.X;int penalty=s.State.Job.Penalty;Click(s);C(s.State.Experiment.Drowsiness==0&&s.State.Experiment.Attention.Cause=="wake:slap");C(s.State.SharedHead.Rotation.X<before&&Math.Abs(s.State.SharedHead.Mass-mass)<.001f&&s.State.Job.Penalty==penalty);C(s.State.Events.Count(e=>e.Text=="Customer slapped awake")==1&&s.ActionLog.Any(a=>a.Actor==1&&a.Kind==PartyAction.Attention));for(int i=0;i<190;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness==0);for(int i=0;i<25;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness>.1f&&s.State.Events.Count(e=>e.Text=="Customer slapped awake")==1,"holding is not repeated slapping");});
        test("AI slap rejects unsafe poses and occupied or disabled hands",()=>{foreach(string reason in new[]{"range","aim","back","wall","tool","prop","down","glue","frozen","disabled","away","human","leaving","resolved","phase"}){var s=Sleeping();var p=s.State.Player(1)!;switch(reason){case "range":p.Position+=Vector3.UnitZ*3;break;case "aim":p.Yaw=MathF.PI;break;case "back":p.Position=new(0,0,-1);break;case "wall":s.ObstructionDistance=(_,_,_)=>.1f;break;case "tool":p.Held=0;break;case "prop":p.CarriedProp=999;break;case "down":p.DownUntil=s.State.Time+2;break;case "glue":p.GlueUntil=s.State.Time+2;break;case "frozen":p.FreezeUntil=s.State.Time+2;break;case "disabled":p.DisabledUntil=s.State.Time+2;break;case "away":p.NetworkAway=true;break;case "human":s.State.Experiment.CustomerActor=2;break;case "leaving":s.State.Experiment.Leave=LeaveStage.Rising;break;case "resolved":s.State.Experiment.Resolved=true;break;case "phase":s.State.Phase=Phase.Results;break;}Click(s);C(!s.State.Events.Any(e=>e.Text=="Customer slapped awake"),reason);}});
        test("AI E still braces; SleepingAI can be slapped awake temporarily",()=>{var s=Sleeping();Click(s,Buttons.Interact);C(s.State.Player(1)!.Bracing&&!s.State.Events.Any(e=>e.Text=="Customer slapped awake"));s=Sleeping();s.State.Twist.Kind=TwistKind.SleepingAI;Click(s);s.Inputs.Clear();for(int i=0;i<70;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness==0);for(int i=0;i<25;i++)s.Tick(.1f);C(s.State.Experiment.Drowsiness>.1f,"sleep twist resumes after wake grace");});
        test("p13 glue drag requires opt-in actual head contact and caps speed without yaw",()=>{var s=World();var p=s.State.Player(1)!;p.AllowDrag=true;p.Position=new(0,0,1.2f);p.Held=0;var t=s.State.Tools[0];t.Holder=1;t.HitHair=true;t.Contact=s.State.SharedHead.Position;t.ContactHead=0;t.LastUse=s.State.Time;foreach(var patch in s.State.SharedHead.Patches)patch.Glue=1;s.Tick(.01f);C(p.GlueHead&&p.GlueUntil<=s.State.Time+3);s.State.Experiment.LeaveStarted=s.State.Time;s.State.SharedHead.Position+=Vector3.UnitX*3;float yaw=p.Yaw;var v=GlueDrag.Velocity(s.State,p,s.State.Time);C(v.Length()<=.80001f&&v.Length()>.7f&&p.Yaw==yaw);p.AllowDrag=false;C(GlueDrag.Velocity(s.State,p,s.State.Time)==Vector3.Zero);p.AllowDrag=true;p.GlueUntil=0;s.Tick(.01f);C(!p.GlueHead);});
        test("p13 returning round preserves volume material and wigs then grows .025",()=>{var s=World(2);s.ReturningEnabled=true;s.MatchRounds=4;s.StartMatch();s.State.SharedHead.Volume.Fill(v=>.48f-new Vector3(v.X,v.Y-.6f,v.Z).Length());foreach(var p in s.State.SharedHead.Patches){p.Glue=.9f;p.Temperature=-30;}var wig=s.State.Heads.First(h=>h.Loose);wig.AttachedTo=0;float mass=s.State.SharedHead.Mass;string profile=s.State.Customers[0].Profile;int first=s.State.Experiment.CustomerActor,card=s.CurrentTarget!.Id;s.NextRound();C(s.State.ReturningHeads&&s.State.SharedHead.Mass>mass&&s.State.SharedHead.Patches.All(p=>p.Glue==.9f&&p.Temperature==-30));C(s.State.Heads.Any(h=>h.Id==wig.Id&&h.AttachedTo==0));C(s.State.Customers[0].Profile==profile&&s.State.Experiment.CustomerActor!=first&&s.CurrentTarget!.Id!=card&&s.State.MatchRounds==4);});
        test("p13 history reveals only completed cards and new match clears history",()=>{var s=World();s.ReturningEnabled=true;s.StartMatch();C(s.State.RoundHistory.Count==0);s.State.Phase=Phase.Build;s.State.Remaining=0;for(int i=0;i<125;i++)s.Tick(.1f);C(s.State.Experiment.Resolved&&s.State.RoundHistory.Count==1&&s.State.RoundHistory[0].Target==s.CurrentTarget);string tag=s.State.MatchTag;int number=s.State.MatchNumber;s.StartMatch();C(s.State.MatchTag!=tag&&s.State.MatchNumber==number+1&&s.State.RoundHistory.Count==0);});
        test("p13 four-player fast motion with 24 props and glue metadata stays below MTU",()=>{var f=new MotionFrame{Sequence=1,Round=2,MatchNumber=3,Time=4,ExpressionKind=1,ExpressionAt=3.9f,Players=Enumerable.Range(1,4).Select(id=>new PlayerMotion(id,1,new(id,0,0),Vector3.Zero,Vector3.Zero,0,0,true,false,GlueHead:true,GlueOffset:new(1,0,0))).ToArray(),Props=Enumerable.Range(0,24).Select(id=>new MovingPose(id,new(id,0,0),Vector3.Zero)).ToArray()};var data=MotionWire.Encode(f);C(data.Length<=1200);var copy=MotionWire.Decode(data);C(copy!=null&&copy.MatchNumber==3&&copy.ExpressionKind==1&&copy.Players.All(p=>p.GlueHead&&p.GlueOffset.X==1));});
    }
}
