using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;

namespace Hairball.Core;

// Presentation-only localization. Network facts, names and recorded English events stay unchanged.
public static class L
{
    public static string Locale { get; private set; } = "en";
    public static event Action? Changed;
    public static string Normalize(string locale) => locale.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? "zh" : "en";
    public static void SetLocale(string locale)
    { var next=Normalize(locale); if(next==Locale)return; Locale=next; Changed?.Invoke(); }
    public static string T(string english,params object[] args)
    { string text=Locale=="zh" && Chinese.TryGetValue(english,out var translated)?translated:english; return args.Length==0?text:string.Format(CultureInfo.InvariantCulture,text,args); }
    public static string PlayerName(string name) => Locale=="zh" ? Regex.Replace(name,@"^Barber ([1-4])$","理发师 $1") : name;
    public static string Text(string text)
    {
        if(Locale!="zh")return text;
        if(Chinese.TryGetValue(text,out var translated))return translated;
        foreach(var (pattern,format) in Patterns)
        {
            var match=Regex.Match(text,pattern);if(!match.Success)continue;
            var args=new object[match.Groups.Count-1];
            for(int i=1;i<match.Groups.Count;i++)args[i-1]=PlayerName(T(match.Groups[i].Value));
            return string.Format(CultureInfo.InvariantCulture,format,args);
        }
        return PlayerName(text);
    }
    static readonly (string,string)[] Patterns =
    [
        (@"^(.*): ordered (.*) \(-([0-9]+)\)$","{0} 订购了 {1}（共享支出 {2}）"),
        (@"^(.*): (Measured rescue|A costly accident|Shared-wallet purchase|One action, many consequences)$","{0}：{1}"),
        (@"^(.*) joined the shared salon$","{0} 加入了共享理发店"),
        (@"^Customer accident: shop -(\d+)$","顾客发生事故：店铺损失 {0}"),
        (@"^Tool impact: (.*), shop -8$","工具撞到了 {0}，店铺损失 8"),
        (@"^Tool force moved (.*)$","气流拉动／推动了 {0}"),
        (@"^(.*) joined station (\d+)$","{0} 加入了 {1} 号工位"),
        (@"^(.*) disconnected$","{0} 已断开连接"),
        (@"^(.*) cashed out$","{0} 已提交作品"),
        (@"^(.*): (.*) → (\d+) head\(s\)$","{0}：{1} → 影响 {2} 个头部"),
        (@"^Station (\d+) KO! Source pays -(\d+)\. Recovery in 4s\.$","{0} 号工位顾客倒地！肇事者扣 {1} 分，4 秒后恢复。"),
        (@"^STATION (\d+)$","{0} 号工位"),
        (@"^(\d+) • HOLD E\nSUBMIT$","{0} 号工位 · 按住 E\n提交作品"),
        (@"^ENet failed: (.*)$","联网失败：{0}")
    ];
    public static readonly IReadOnlyDictionary<string,string> Chinese = new Dictionary<string,string>
    {
        ["Picked up the shop cat"]="抱起了店猫",
        ["Blower shooed the cat"]="吹风机赶开了店猫",
        ["Shop cat: Sleep"]="店猫：跳上头睡觉",
        ["Shop cat: Steal"]="店猫：叼走轻物",
        ["Shop cat: Swat"]="店猫：拍下委托物",
        ["Hand bonded to glued customer hair"]="手粘在了顾客头发上",
        ["Customer slapped awake"]="一巴掌拍醒了顾客",
        ["LMB: recycle 60% (charred 30%); RMB: patch with stored hair"]="左键：回收六成（焦发三成）；右键：储存碎发补洞",
        ["WIG PATCH · GLUE / FREEZE / NAIL"]="假发补丁 · 上胶 / 冰冻 / 锚钉",
        ["That's ridiculous. I love it!"]="太离谱了，我喜欢！",
["How does that even stay up?"]="这居然撑得住？",
["Well, at least we got a photo."]="好吧，至少还有照片。",
["Thanks! I'll take it from here."]="谢谢！接下来我自己来。",
["Base pay"]="基本工钱",
["Tip"]="小费",
["Shop wallet"]="店铺余额",
["Customer / world"]="顾客 / 环境",
["PHOTO WALL · LOCAL MEMORIES"]="照片墙 · 本机留念",
["INCOMPLETE"]="未完成",
["lit hair"]="点着了头发",
["extinguished hair"]="灭了头发上的火",
["picked up the commission"]="拿起了委托物",
["placed the commission"]="放上了委托物",
["attached a wig"]="贴上了假发",
["glued hair"]="给头发上胶",
["froze hair"]="冻住了头发",
["rang the bell"]="敲响了铃",
["seated the customer again"]="把顾客按回座位",
["braced during departure"]="离店时扶稳了头",
["emptied a bottle"]="用空了一瓶",
["punctured a mold"]="打穿了模具",
["froze a teammate"]="冻住了队友",
["glued a teammate's hands"]="粘住了队友的手",
["lit a teammate's hair"]="点着了队友的头发",
["thawed a teammate"]="解冻了队友",
["freed sticky hands"]="解开了粘手",
["extinguished a teammate"]="给队友灭了火",
["clipped a teammate's hair"]="剪了队友的头发",
["recycled loose hair"]="回收了碎发",
["blew a prop loose"]="吹落了道具",
["caught the customer's attention"]="吸引了顾客注意",
        ["MOLD · PINNED"]="模具 · 已钉住",
["MOLD · HOLD OR PIN"]="模具 · 需要扶住或钉住",
["COMBO WALL"]="组合墙",
["Frozen hair shatters under a heavy hit"]="冻硬的头发受重击会碎",
["Heat loosens glue"]="热会让胶失效",
["Wind carries mist and flame"]="风会带走水雾和火",
["Wet hair resists ignition"]="湿头发不容易点着",
        ["Hold mold against hair; a teammate sprays. Nail to fix; E places; G drops."]="把模具贴在头发上，由队友喷生长剂；锚钉固定，E 放置，G 丢下。",
        ["Completion bell"]="完工铃",
        ["E: leave early"]="E：提前离店",
        ["Place the commission first"]="先把委托物放在头上",
        ["Completion bell rang"]="完工铃响了",
        ["Seated"]="坐着施工",
        ["Rising"]="即将起身",
        ["ToMirror"]="走向镜子",
        ["Mirror"]="照镜子",
        ["ToDoor"]="走向门口",
        ["Done"]="到达门口",
        ["RC HELICOPTER"]="遥控直升机",
        ["Put the helicopter on the hair. Keep it supported until the customer reaches the door."]="把直升机放在头发上，护送顾客到门口时仍有支撑。",
        ["E: pick up / place; hold E: brace; G: drop"]="E 拿放；按住 E 扶头；G 丢下",
        ["Seat delay remaining"]="还能按回座位",
        ["Place anywhere; test without ending the round."]="自由放置，试放不会结束本局。",
        ["Support stable"]="支撑稳定",
        ["Commission slipped"]="委托物滑落",

        ["Ow, hot! Water, please!"]="好烫！快拿水来！",
        ["Put it out! I am about to leave!"]="快灭火！我快受不了了！",
        ["I cannot take it! Customer fled."]="受不了了！顾客跑了。",
        ["Brr! My hair is frozen!"]="好冷！头发冻住了！",
        ["I am soaking wet!"]="我湿透了！",
        ["Something on my head? Keep it steady!"]="头上放了东西？帮我扶稳！",
        ["Let me see that in the mirror!"]="让我照照镜子！",
        ["My neck is getting sore!"]="脖子好酸！",
        ["Twenty seconds. I need to leave soon."]="还有二十秒，我快要走了。",
        ["Where is my coat? Ten seconds!"]="外套呢？还有十秒！",
        ["Customer tolerance"]="顾客忍耐",
        ["No fire: cooling down"]="没有火：正在缓和",

        ["Helicopter called. Keep building during approach."]="已呼叫直升机，进近期间仍可施工。",
        ["Trial landing failed. Repair the support, then call again."]="试落未成功。修补支撑后可以再次呼叫。",
        ["Helicopter ready. Repair the pad and call when ready."]="直升机已待命。修补停机坪，准备好后再次呼叫。",
        ["Shallow finishing removal • RMB fine"]="浅层精修 · 右键细修",
        ["Extrude soft Young hair • wind carries mist"]="沿表面长出柔软新发 · 风会吹偏喷雾",
        ["LMB push • RMB press / organize existing hair"]="左键推移 · 右键压整现有头发",
        ["Join touching hair • fix shape • heat releases"]="粘合接触的头发 · 固定造型 · 加热解胶",
        ["LMB level plane • RMB aim-facing sever"]="左键水平削切 · 右键沿瞄准方向切断",
        ["E interact · G drop · Space jump · R/F chair · Tab board · H ghost · Esc options"]="E 互动 · G 丢下 · 空格跳跃 · R/F 座椅 · Tab 参考板 · H 辅助轮廓 · Esc 设置",
        ["JOB PROP • E place · R/F tilt · G drop"]="任务道具 · E 放置 · R/F 倾斜 · G 丢下",
        ["E • CARRY JOB PROP"]="E · 搬起任务道具",

        ["FRONT"]="正面",["SIDE"]="侧面",["TOP"]="俯视",
        ["TARGET MODEL • protected"]="目标模型 · 受保护",
        ["PRACTICE MODEL • E carry • tools affect hair"]="练习模型 · E 搬起 · 工具可修改头发",
        ["E • CARRY PRACTICE MODEL"]="E · 拿起练习模型",
        ["PRACTICE MODEL • E / G put down"]="搬运练习模型 · E / G 放下",
        ["Char the outer rim • place the candles"]="烧焦外圈 · 摆放蜡烛",
        ["Soft nest • place three eggs"]="柔软鸟窝 · 放入三颗蛋",
        ["Flat + firm • helicopter landing"]="平整且坚固 · 直升机降落",
        ["Shape + material + real prop test"]="形状 + 材料 + 实物测试",
        ["Water Mister"]="喷水壶",["Wet hair • damp heat and weaken fresh glue"]="浸湿头发 · 抵御热量并削弱新胶",
        ["Trim three tiers. Char the outer rim and place five candles upright."]="剪出三层蛋糕。烧焦外圈，摆正五根蜡烛。",
        ["JOB PROPS • E carry / place"]="任务道具 · E 搬起 / 放置",
        ["Normal"]="普通",["Young"]="新生",["Wet"]="湿润",["Frozen"]="冰冻",["Glued"]="胶固",["Charred"]="焦化",
        ["Shape {0:0} · Material {1:0} · Function {2:0} · Total {3:0}"]="形状 {0:0} · 材料 {1:0} · 功能 {2:0} · 总评 {3:0}",

        ["Growth Burst"]="爆发生发罐",["Cryo Canister"]="急冻罐",
        ["SHARED ORDERS"]="共享订购台",["BURST $35"]="生发 $35",["CRYO $25"]="急冻 $25",["CANCEL"]="取消",
        ["SHOP WALLET ${0}"]="共享钱包 ${0}",["PENDING {0:0.0}s · shared ${1}"]="待确认 {0:0.0}秒 · 共享支出 ${1}",
        ["E · Cancel pending order"]="E · 取消待确认订单",
        ["E · Order {0} · shared ${1} / wallet ${2}"]="E · 订购{0} · 共享支出 ${1}／余额 ${2}",
        ["{0} is ordering {1} · shared ${2}\n{3:0.0}s to cancel at the red terminal button"]="{0} 正在订购{1} · 共享支出 ${2}\n{3:0.0}秒内可在订购台红色按钮取消",
        ["Not enough shared money."]="共享余额不足。",["Use the delivered specials first."]="请先使用已经送达的特殊工具。",
        ["Order pending — anyone may cancel."]="订单待确认——任何人都可以取消。",["Order cancelled. No money spent."]="订单已取消，没有扣款。",
        ["Special delivered — shared wallet charged."]="特殊工具已送达，共享钱包已扣款。",
        ["ONE USE · LMB burst · affects nearby hair"]="一次性 · 左键释放 · 波及附近毛发",["EMPTY · drop with G"]="已用完 · 按 G 丢弃",
        ["SPOTLIGHT — stories, not a winner"]="本单人物小记",
        ["Biggest Contributor"]="造型功臣",["Rescue Barber"]="救场理发师",["Biggest Accident"]="最大事故",["Chaos Magnet"]="混乱磁铁",
        ["Big Spender"]="大手笔买家",["Risky Genius"]="冒险天才",["Last-Second Save"]="最后一刻救场",["Self-Hair Victim"]="自己的头发遭殃了",
        ["Measured rescue"]="挽救了作品",["A costly accident"]="代价不小的事故",["Shared-wallet purchase"]="共享钱包买单",
        ["One action, many consequences"]="一招引发连锁反应",["Customer / environment"]="顾客／环境",
        ["Llama customer • watch those cheeks!"]="羊驼顾客 · 留意鼓起的脸颊！",
        ["Human customer • steady hands, please!"]="人类顾客 · 手要稳一点！",
        ["* cheeks puff *"]="* 鼓起脸颊 *",
        ["Llama spit — mind the warning!"]="羊驼吐口水了——留意预警！",
        ["SHARED JOB • {0}\n{1}"]="共享任务 · {0}\n{1}",
        ["ONE SHARED CUSTOMER • EVERYONE HELPS"]="同一个顾客 · 全员共享任务",
        ["VOTE TOGETHER • 1 / 2 / 3\nYour vote: {0}"]="共同投票 · 1 / 2 / 3\n你的选择：{0}",
        ["Not voted"]="尚未投票",
        ["ARRIVAL"]="顾客入座",["PREVIEW"]="目标预览",
        ["SHARED RESULT\nShape {0:0} / 100 · Validation {1}\nIncidents -{2} · Job {3:+0;-0;0}\nSpecial orders -{5} · SHOP WALLET {4}"]="共享结算\n造型 {0:0} / 100 · 验收{1}\n事故 -{2} · 本单 {3:+0;-0;0}\n特殊订购 -{5} · 店铺资金 {4}",
        ["PASSED"]="通过",["FAILED"]="失败",
        ["SHOP BANKRUPT · {0}"]="店铺破产 · 资金 {0}",
        ["THREE SHARED JOBS COMPLETE · WALLET {0}"]="三个共享任务完成 · 店铺资金 {0}",
        ["One customer. One shared job."]="同一个顾客，同一个共享任务。",
        ["Customer braces before moving"]="顾客绷紧身体，要动了……",
        ["Helicopter approaching — rotor wash"]="直升机正在靠近——小心旋翼气流",
        ["* inhale *"]="（倒吸一口气）",["Huh?!"]="嗯？！",["Whoa!"]="哇！",
        ["4 BARBERS / 1 HEAD"]="四个理发师／同一个头",
        ["WASD move • Space jump • R/F chair   Mouse aim   E pick up / place   LMB use   RMB alternate   G drop   Esc cursor   F3 debug"]="WASD 移动 · 空格跳跃 · R/F 座椅 · 鼠标瞄准 · E 拿放 · 左键使用 · 右键副功能 · G 丢弃 · Esc 光标 · F3 调试",
        ["Pick up physical tools from the side benches.\nAim at the cyan target around your customer.\nAll players work on the same customer.\nAccidents cost the shared shop money."]="从两侧工作台拿起实体工具。\n青色轮廓提示共享顾客的目标形状。\n所有玩家一起给同一位顾客理发。\n事故会损失共同的店铺资金。",
        ["LMB normal • RMB fine • Wheel size: {0}"]="左键常规 · 右键精修 · 滚轮调范围：{0}",
        ["Small"]="小",["Medium"]="中",["Large"]="大",
        ["ROUND {0}/3 · HAIR LAB"]="第 {0}/3 回合 · 理发实验室",
        ["ROUND {0}/3 · {1:00}s"]="第 {0}/3 回合 · {1:00} 秒",
        ["STATION {0}  •  {1}\n{2}"]="{0} 号工位 · {1}\n{2}",
        ["Two supports. One crossbar. Three pairs. [Tab] target"]="两根支柱，一根横梁，三条内裤。Tab 查看目标",
        ["E interact · G drop · Space jump · R/F chair · Tab target · Esc options"]="E 互动 · G 丢下 · 空格跳跃 · R/F 座椅 · Tab 目标 · Esc 设置",
        ["LAUNDRY LAB — risky finishing touches"]="晾衣架实验室 — 危险的最后修补",
        ["Reservoir full. Transfer hair with RMB before collecting more."]="储量已满，先用右键转移头发，再继续吸取。",
        ["HAIRBALL"]="毛球理发店",
        ["A salon for questionable engineering.\n1–4 barbers · 3 rounds · 75 seconds"]="一家专做离谱发型工程的理发店。\n1–4 位理发师 · 3 个回合 · 每回合 75 秒",
        ["Host address"]="主机地址",
        ["SOLO — start cutting"]="单人游戏 — 开始理发",
        ["HOST — open shared salon"]="创建房间 — 开一家共享理发店",
        ["JOIN — direct ENet"]="加入房间 — 连接指定主机",
        ["HAIR LAB — experiment without a timer"]="毛发实验室 — 不限时自由尝试",
        ["Pick up physical tools from the side benches.\nAim at the cyan target around your customer.\nGreen station button: hold E to submit safely.\nDangerous accidents penalize the source."]="从两侧工作台拾取工具。\n对照顾客头部周围的青色目标进行造型。\n瞄准工位绿色按钮，按住 E 提交并保护作品。\n引发危险事故的玩家会被扣分。",
        ["WASD move • Space jump • R/F chair   Mouse aim   E pick up / hold at SUBMIT   LMB use   RMB alternate   G drop   Esc cursor   F3 debug"]="WASD 移动  空格跳跃  R/F 座椅   鼠标瞄准   E 拾取／按住提交   左键使用   右键副功能   G 丢弃   Esc 鼠标   F3 调试",
        ["START MATCH [Enter]"]="开始比赛 [Enter]",
        ["PLAY AGAIN [Enter]"]="再来一局 [Enter]",
        ["MENU"]="主菜单",
        ["RESET LAB [F5]"]="重置实验室 [F5]",
        ["Connecting to the host…"]="正在连接主机……",
        ["Session closed"]="已退出房间",
        ["Could not connect. Check address/port and host firewall."]="连接失败。请检查地址、端口和主机防火墙。",
        ["Host disconnected. Session ended safely."]="主机已断开连接，已安全退出房间。",
        ["LOBBY"]="等候室", ["CHOICE"]="选择目标", ["BUILD"]="造型时间", ["VALIDATION"]="目标验证",
        ["RESULTS"]="回合结算", ["HIGHLIGHT"]="精彩回放", ["COMPLETE"]="比赛结束",
        ["{0}   /   ROUND {1}/3   /   {2}   {3:00}s"]="{0}   /   第 {1}/3 回合   /   {2}   {3:00} 秒",
        ["STATION {0}  •  {1}\n{2}\n{3}"]="{0} 号工位  •  {1}\n{2}\n{3}",
        ["Rough shape match: {0:0}%  •  Cyan outline = target from this view  •  {1}"]="造型匹配约 {0:0}%  •  青色轮廓为当前视角的目标  •  {1}",
        ["SUBMITTED — protected"]="已提交 — 作品受保护", ["Work is still live"]="作品仍可被改动",
        ["EMPTY HANDS  •  Aim at a bench tool and press E"]="双手空空  •  瞄准工作台上的工具，按 E 拾取",
        ["{0} charges"]="剩余 {0} 次", ["Stored hair {0:0.0}/20"]="储存毛发 {0:0.0}/20",
        ["WORK PROTECTED"]="作品已受保护", ["HOLD E TO SUBMIT  [{0:0}%]"]="按住 E 提交作品  [{0:0}%]",
        ["E  •  PLACE / WEAR HAIR BUNDLE"]="E  •  放置／戴上假发或毛发团",
        ["SHARED SALON\n{0}\n\n{1}"]="共享理发店\n{0}\n\n{1}", ["Station {0} • {1}"]="{0} 号工位 • {1}",
        ["Start when everyone has joined."]="所有玩家加入后即可开始。", ["Waiting for host to start."]="等待主机开始比赛。",
        ["ROUND RESULTS\nShape × 70%  +  Test × 20%  +  Props × 10%  −  Incidents\n\n"]="回合结算\n造型 × 70%  +  功能验证 × 20%  +  道具 × 10%  −  事故扣分\n\n",
        ["{0}: {1:0} / {2:0} / {3:0}  −{4:0}  =  {5:0} pts"]="{0}：{1:0} / {2:0} / {3:0}  −{4:0}  =  {5:0} 分",
        ["MATCH COMPLETE\nWINNER: "]="比赛结束\n获胜者：", ["{0}  •  {1:0} points"]="{0}  •  {1:0} 分",
        ["BEST MOMENT\n{0}"]="精彩时刻\n{0}", ["{0}  •  SPECTATOR\n{1} / {2} still holding"]="{0}  •  观战视角\n{1} / {2} 个道具仍保持稳定",
        ["YOUR HAIR • LIVE MIRROR\nFire {0}   Ice {1}   Glue {2}\n{3}"]="你的头发 • 实时镜像\n燃烧 {0}   冻结 {1}   胶水 {2}\n{3}",
        ["HAIR PINNED — move to pull free"]="头发被钉住了 — 移动以挣脱", ["Survives all three rounds"]="发型状态延续整场比赛",
        ["YOUR HAIR • LIVE MIRROR"]="你的头发 • 实时镜像", ["YOUR HAIR • LIVE PORTRAIT"]="你的头发 • 实时影像",
        ["[LOCKED]"]="[已保护]", ["RECOVERING"]="恢复中", ["INACTIVE STATION"]="空闲工位",
        ["HAIRBALL\nGOOD HAIR. QUESTIONABLE METHODS."]="毛球理发店\n发型要好，手段随意。",
        ["SAFE-ISH SUPPLIES"]="大概安全的工具", ["REGRETTABLE SHORTCUTS"]="可能会后悔的捷径",
        ["WIGS • AIM + E TO WEAR / PLACE\nGlue holds. Wind steals."]="假发 • 瞄准后按 E 戴上／放置\n胶水能粘住，风会吹走。",
        ["Welcome to Hairball"]="欢迎来到毛球理发店",
        ["Choose your commission. Tools are on the side benches."]="选择本回合目标。工具放在两侧工作台上。",
        ["Make something irresponsible. Hold E at your green SUBMIT button to lock it."]="放手做个离谱发型吧！瞄准绿色提交按钮，按住 E 保护作品。",
        ["Match complete"]="比赛结束", ["Wig attached — glue it before the wind does its thing"]="已戴上假发 — 趁风吹走之前用胶水固定好",
        ["A hard day's questionable work"]="辛苦一天，成果令人担忧",
        ["CHAIR  R ↑ / F ↓"]="座椅  R 升 / F 降",
        ["E • MOVE LADDER"]="E 搬动梯子",
        ["Not enough room to place the ladder."]="这里放不下梯子，请移到空地。",
        ["CARRYING LADDER • G / E to place on clear floor"]="正在搬梯子 • G / E 放到空地上",
        ["G • PLACE LADDER — clear floor required"]="G 放下梯子 · 需要足够空地",
        ["E • CARRY LADDER / walk up steps to stand"]="E 搬起梯子 / 沿踏步走上平台",
        ["R / F • RAISE / LOWER CHAIR ({0:0.00} m)"]="R 升高 / F 降低座椅（{0:0.00} 米）",
        ["No hair surface under aim"]="未瞄准头发表面",
        ["Head {0} • Volume {1:0.0}\nHeat {2:0} Glue {3:0.0} Anchored {4}"]="头部 {0} • 体积 {1:0.0}\n温度 {2:0} 胶水 {3:0.0} 已锚定 {4}",
        ["No hair tip under aim"]="未瞄准毛发末端",
        ["Head {0} patch {1} • L {2:0.00}\nHeat {3:0} Glue {4:0.0} Anchored {5}"]="头部 {0} 毛发块 {1} • 长度 {2:0.00}\n温度 {3:0} 胶水 {4:0.0} 已锚定 {5}",
        ["HOST AUTHORITY"]="主机权威", ["CLIENT"]="客户端", ["Yes"]="是", ["No"]="否",
        ["Peer {0}  {1}\nFacts revision {2} • compressed {3} bytes\nHeads {4} / patches {5}\nGoal {6} • Shop damages {7}\n{8}\nLAB: F5 reset • F6 wig • F7 target"]="玩家 {0}  {1}\n状态版本 {2} • 压缩后 {3} 字节\n头部 {4} / 毛发块 {5}\n目标 {6} • 店铺损失 {7}\n{8}\n实验室：F5 重置 • F6 假发 • F7 目标",
        ["Precision Clipper"]="精密电推剪", ["Trim a small patch safely"]="安全修剪一小块毛发",
        ["Super Growth Spray"]="超级生发喷雾", ["Grow material • wind carries mist"]="让毛发生长 • 风会吹偏喷雾",
        ["TOOLS ARE SUPPLIED"]="工具已配给",["used tool"]="使用了工具",["Secret tasks (host setting)"]="秘密任务（房主设置）",["Show secret task"]="展开秘密任务",["Hide secret task"]="收起秘密任务",["Your secret task"]="你的秘密任务",["No score · revealed at results"]="不计分 · 结算时揭晓",["Secret tasks · no score"]="秘密任务 · 不计分",["Done"]="完成",["Not done"]="未完成",
        ["Frozen · teammate tap to rescue"]="冻住了 · 队友敲一下可救",["Sticky hands · heat to rescue"]="粘手了 · 热风或火焰可救",["Hair on fire · water to rescue"]="头发着火 · 喷水可救",
        ["Clip a teammate's hair once"]="给队友剪一刀头发",["Freeze a teammate once"]="冻住一次队友",["Make the customer look at you"]="让顾客转头看你一次",["Attach a wig that stays until the door"]="让你装的假发留到离店",["Blow a prop loose"]="用吹风机吹落一件道具",["Ring the completion bell"]="敲响完工铃",["Freeze some customer hair that stays frozen at the door"]="让你冻的顾客头发留到离店",["Recycle loose hair"]="回收一次碎发",["Brace the head during departure"]="在离店途中扶稳头部",["Rescue a teammate from an accident"]="救助一次中招的队友",
        ["Transfer Cannon"]="毛发转移炮", ["LMB suck / RMB transfer stored hair"]="左键吸取／右键喷出储存的毛发",
        ["Industrial Blower"]="工业吹风机", ["Bend hair • blow wigs, mist and fire"]="吹弯毛发 • 吹走假发、喷雾和火焰",
        ["Hot Glue Gun"]="热熔胶枪", ["Stiffen shape • secure wigs near a head"]="加固造型 • 固定头部附近的假发",
        ["Liquid Nitrogen"]="液氮枪", ["Freeze rigid • heavy impacts shatter"]="冻结并硬化毛发 • 强烈冲击会使其碎裂",
        ["Anchor Gun"]="锚钉枪", ["Pin hair tips in space • stretch moving hair"]="固定毛发末端 • 移动会拉扯被钉住的头发",
        ["Hair Sniper"]="毛发狙击枪", ["Puncture through aligned targets / RMB zoom"]="贯穿直线上的目标／右键放大瞄准",
        ["Flamethrower"]="火焰喷射器", ["Fast removal • heat thaws and fire spreads"]="快速烧除毛发 • 高温解冻，火焰蔓延",
        ["Hedge Trimmer"]="绿篱修剪机", ["Broad level cut at crosshair height"]="沿准星高度大范围削平毛发",
        ["Helipad"]="头顶停机坪", ["Grow a broad flat top, then glue or freeze it for landing."]="长出宽而平的顶部，再用胶水或液氮加固，迎接直升机降落。", ["LANDING / rotor wash"]="降落测试／旋翼气流",
        ["Bird Nest"]="鸟巢发型", ["Grow a rim; clear the middle to hold three eggs during a spin."]="长出鸟巢边缘，清空中间，让三颗鸟蛋在座椅旋转时不掉落。", ["EGGS / chair spin"]="鸟蛋测试／座椅旋转",
        ["Rocket Silo"]="火箭发射井", ["Grow a tall ring. Clear the central launch tunnel."]="长出高高的环状结构，清空中央发射通道。", ["LAUNCH / tunnel clearance"]="发射测试／通道净空",
        ["Cat Tree"]="猫爬架发型", ["Grow a tall trunk and a broad top; stiffen it for the cat."]="长出高高的支柱和宽阔的顶部，加固它，让猫咪爬上去。", ["CAT / climb and stay"]="猫咪测试／攀爬与停留",
        ["Birthday Cake"]="生日蛋糕发型", ["Trim three tiers. Keep five candles upright and hair unburnt."]="修出三层蛋糕，让五根蜡烛保持直立，别把头发烧着了。", ["CANDLES / five flames"]="蜡烛测试／五点烛光",
        ["Hair Bridge"]="毛发大桥", ["Grow and bend a connected span, then glue or anchor it."]="让毛发生长并弯成连贯的桥面，再用胶水或锚钉固定。", ["CART / cross the span"]="小车测试／驶过桥面",
        ["Underwear Line"]="内裤晾衣架", ["Make two tall posts and a stiff crossbar for three pants."]="做出两根高柱和坚固的横梁，挂住三条内裤。", ["FAN / laundry test"]="风扇测试／晾晒内裤",
        ["Toilet Hair"]="马桶发型", ["Make a deep bowl with an open center. Hold and flush water."]="做出中央开口的深碗结构，先蓄水，再冲水。", ["WATER / fill and flush"]="流水测试／蓄水与冲水"
    };
}
